export const lightTheme = {
  bg: "#FAFAFA",
  primary: "#146EB4",
  menubar: "#1E2640",
  menu_hover: "#ffffff1a",
  menu_primary_text: "#FFF",
  menu_secondary_text: "#b1b2b3",
  menu_card: "#353C53",
  navbar: "#FFF",
  navbar_border: "#D9D9D9",
  text_primary: "#1A181E",
  text_secondary: "#4D4D4D",
  searchBar: "#F2F2F2",
  searchBar_text: "#808080",
  tableSearchBar_text: "#999",
  card: "#FFFFFF",
  tableHeading_bg: "#F2F2F2",
  tableDivider: "#e6e6e6",
};
